### PR TITLE
Added option for displaying full paths

### PR DESCRIPTION
**Pull request by PeterWillumsen**
Hey,

Great app. 
I don't know if you a looking for contributions, but I wanted the option of showing full paths, instead of just the repository names. So I have added it as an option in the config. It is off by default.

`tms config --full-path true` to enable

I'm not sure how you handle version numbers, but i just bumped the patch.

### CODE REVIEW

**Comment by jrmoulton** [comment]
This looks great! Thanks for the PR!

The one thing I would change is that I would make the full path flag not take any values. The presence of the flag should be enough to indicate true vs false

**Comment by jrmoulton** [comment]
Actually I just used this and because this is inside of the config subcommand the way you have it is definitely the right way. I'll go ahead and merge this!

Thanks for the PR!!

**Comment by PeterWillumsen** [comment]
I think that would work if it was a flag that you just used if you wanted to show the full path one time. Like `tms --full-path`.
 
But as it is now it is under the config subcommand so it can be persistent. So you can't just omit the flag if you want to turn it off again. `tms config` would just show the help for the config options.

 But i agree that a true/false flag usually should just be indicated by its presence. Could change the words to enable/disable instead of true/false, but it is kind of the same. Otherwise i'm not sure of the best way.

**Comment by PeterWillumsen** [comment]
Oh i see you already merged. So just ignore the last comment. Thank You 👍🏼

**Pull request merged**
