### PR TITLE
Add Automated Binary Releases with GitHub Actions

### PR DESCRIPTION
**Pull request by stefhol**
Hi,

I've been trying to use tms in a docker container but I failed because I could not install the whole rust toolchain. So I started looking how to get some prebuild binaries and found other repositories using git2 [buckle](https://github.com/benbrittain/buckle). I noticed the beautiful release page and realized that this is very easy to achieve.

I've set up an automated release process using GitHub Actions. This was auto generated by cargo-dist 

Implementation:
- Modified `Cargo.toml` and included a GitHub Actions workflow + Cargo Dist Config.
- The workflow utilizes `cargo-dist` ([link](https://github.com/axodotdev/cargo-dist)) to generate GitHub Actions file.
- The pipeline triggers when a commit is tagged with the format `v1.1.1`, ensuring the tag version matches the version in `Cargo.toml`.
- Alternatively, releases can be triggered using `cargo release v1.1.1`.

Outcome:
This implementation results in a structured release page [My tmux-sessionizer release page](https://github.com/stefhol/tmux-sessionizer/releases). Note: Some links might be broken as they reference the original repository instead of the fork. These have been manually adjusted to point to my repository for demonstration.

My Changes can be reduced to the Cargo.toml. The provided cargo dist config in there is generating the workflow file.
And I needed to have the openssl vendored or my musl build on the github server would fail

Cheers

### CODE REVIEW

**Comment by jrmoulton** [comment]
Thanks!!! I've really been wanting to add binary releases. 

I'm going to take a few days to look into cargo-dist and a little more into GitHub Actions but this looks great!

**Comment by jrmoulton** [comment]
I'm new to GitHub Actions. Is the process for creating a release still the same and then on creating a release the action will run and tag the binaries to the release page?

**Comment by stefhol** [comment]
Yeah it's automatic the only important thing is that the git tag and the cargo.toml release has to the same version. If not the pipeline fails

I used cargo-release because I forget always something.
But its really just 
git push
git tag v1.1.1
git push origin v1.1.1
The pipeline is running at this point and if it is finished a release is created with the assets. If it fails then there is no release.

cargo-dist is only needed if you want to update the workflow config or create it

**Comment by jrmoulton** [comment]
This looks good to me and I think I'm good to merge it. 

@petersimonsson any opinions?

**Comment by petersimonsson** [comment]
@jrmoulton looks reasonable to me

**Comment by jrmoulton** [comment]
Thanks! @stefhol

**Pull request merged**
