### PR TITLE
Add marks feature

### LINKED ISSUE #132: Bookmarks feature
This is more of a draft of an idea at this point, but especially for times when I'm switching between a small number of projects frequently, it would be really nice to be able to bookmark certain projects to be able to jump to them directly using a single hotkey.
The way I envision it right now is that in my tmux config, I would bind e.g. 4 keys to open bookmarks 1-4, and then either via the config file or maybe even by running `tms bookmark set 2` in a git repo, that repo would get assigned to that number and I could open it directly by using my hotkey bound to bookmark 2.
Is this something that would be useful to other people? Are there any alternative suggestions for something similar? I would be open to implementing it, but I'd like to have these answered first before getting started.

### PR DESCRIPTION
**Pull request by junglerobba**
closes #132

This fulfills what I would require of such a feature, but I'm taking suggestions of course.
(Including naming, unfortunately `bookmark` was already taken)
EDIT: Feel free to disregard the second commit if you want, I just wanted to test out this clap feature and I just so happened to have a perfect case right here

### CODE REVIEW

**Comment by junglerobba** [comment]
with fish this is how the dynamic shell completions look like:
image

**Comment by jrmoulton** [comment]
This looks great. Thanks!

**Comment by brumik** [comment]
Hello, probably not the best place to ask, but when will be this feature released? I see last release from Okt. 28, bit more than 3 months ago.

**Comment by jrmoulton** [comment]
I'll see about getting one out this weekend. Thanks for the reminder :)

**Comment by junglerobba** [comment]
As an alternative, since I use it myself I try to make sure that the nix flake package provided in this repo keeps working :) that way you don’t need to rely on tagged releases

**Pull request merged**
